# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'WeChat Work' do
  use_frameworks!
  
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'UMCCommon'
  
  pod 'IQKeyboardManager'
  pod 'SCLAlertView-Objective-C'
  pod 'DZNEmptyDataSet'
  pod 'PhotoBrowser'
  
end
